### PR TITLE
Remove unnecessary NFC flags and packages

### PR DESCRIPTION
**Pull request by luk1337**
* These packages and flags no longer exist
  in AOSP 9 codebase.

### CODE REVIEW

**Comment by jerpelea** [comment]
the firmware is needed

https://github.com/sonyxperiadev/vendor-nxp/blob/master/Android.mk

**Comment by jerpelea** [comment]
NXP_CHIP_TYPE is not used

**Comment by luk1337** [comment]
oh, i'll readd it in a moment then lol.

**Comment by luk1337** [comment]
~ bump ~

**Pull request merged**
