### PR TITLE
Update thermanager.xml to match with stock

### PR DESCRIPTION
**Pull request by RyTekk**

### CODE REVIEW

**Comment by jerpelea** [comment]
which kernel is used?

**Comment by RyTekk** [comment]
What do you mean? I just update following thermal-engine.conf.

**Comment by jerpelea** [comment]
depending on kernel version sysfs paths will change

**Comment by RyTekk** [comment]
I checkout a new branch from master branch. I just added 1.8GHz step for big cluster.

**Comment by jerpelea** [comment]
ok
so you used the 4.4 kernel 
the same change should be pushed to dora ad keyaki

**Pull request closed without merging**
