### PR TITLE
[master] kagura: thermanager: Add charging limits

### PR DESCRIPTION
**Pull request by humberos**
Signed-off-by: Humberto Borba <humberos@gmail.com>
Change-Id: I325425d09e587b31959c1f52447888d49b67b9a3

### CODE REVIEW

**Comment by humberos** [comment]
ping @kholk

**Comment by kholk** [comment]
Are you sure that the values are in milliDegC?

**Comment by humberos** [comment]
nope!
I need help here.

**Comment by humberos** [comment]
the logic was extracted from satsuki

**Comment by kholk** [comment]
Sony is not scaling with that.... whatever, I can find some time to check... but it's probably in deciDegC

**Comment by humberos** [comment]
ok, thanks!

**Pull request closed without merging**
